services:
  - type: web
    name: jeunact-badges-qr
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: JeunAct2024_QR_Code_SuperSecretKey_ChangeInProduction
