name = "qr-code-jeunact"
main = "worker.py"
compatibility_date = "2023-12-01"
compatibility_flags = ["python_workers"]

# Configuration pour la production 24/7
[env.production.vars]
ENVIRONMENT = "production"
SECRET_KEY = "your-secret-key-here"
PRODUCTION_URL = "https://qr-code-jeunact.your-domain.workers.dev"
DATABASE_URL = "postgresql://postgres:password@db.project-ref.supabase.co:5432/postgres"
CLOUDFLARE_WORKER = "true"
CLOUDFLARE_WORKER_URL = "https://qr-code-jeunact.your-domain.workers.dev"

# Configuration pour le staging
[env.staging.vars]
ENVIRONMENT = "staging"
SECRET_KEY = "your-staging-secret-key"
PRODUCTION_URL = "https://qr-code-jeunact-staging.your-domain.workers.dev"
DATABASE_URL = "postgresql://postgres:password@db.project-ref-staging.supabase.co:5432/postgres"
CLOUDFLARE_WORKER = "true"
CLOUDFLARE_WORKER_URL = "https://qr-code-jeunact-staging.your-domain.workers.dev"

# Configuration pour le stockage des photos (Cloudflare R2)
[[r2_buckets]]
binding = "PHOTOS_BUCKET"
bucket_name = "jeunact-photos"
preview_bucket_name = "jeunact-photos-preview"

# Configuration pour la base de données KV (backup optionnel)
[[kv_namespaces]]
binding = "MEMBERS_KV"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"
